version: '3.8'

services:
  web:
    image: zaffarwani/farmly:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    labels:
      - "current_farmly_container"
    networks:
      - webnet

networks:
  webnet:
